### ISSUE TITLE
主题实装

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/img-decoration#5]
## 主页风格：author

https://www.jx3box.com/author/8
个人主页更换为线上接口

- [x] 已完成

**Comment by iRuxu** [comment]
## 侧边栏主题

其它cms栏目的个人名片接口更换

<img width="466" alt="image" src="https://github.com/user-attachments/assets/0214d5cb-0e44-4736-878f-3302aea74ae8">


- [x] 已完成

**Comment by iRuxu** [comment]
## 论坛

论坛的个人卡片 新增上实装上侧边栏主题风格

<img width="328" alt="image" src="https://github.com/user-attachments/assets/8077b471-3695-4e86-af1f-b3c017622d61">


- [x] 已完成

**Comment by iRuxu** [comment]
## 首页日历

更换为新接口

<img width="455" alt="image" src="https://github.com/user-attachments/assets/52575907-7270-4dd1-822e-84464c6f5918">

在index库

- [x] 已完成

**Comment by iRuxu** [comment]
## 评论皮肤

更换新接口？
在评论组件

- [x] 已完成

**Comment by iRuxu** [comment]
## 圈人卡

更换上对应的接口
是文章正文的圈人卡，在jx3box-editor库

- [x] 已完成

**Comment by iRuxu** [comment]
## 魔卡

更换上对应的接口
在bbs项目

- [ ] 已完成

**Comment by Kaviilee** [comment]
> ## 魔卡
> 更换上对应的接口 在bbs项目
> 
> * [ ]  已完成

-----
魔卡用的不是index.json，此外我发现还有另一个json
![image](https://github.com/user-attachments/assets/39cc9621-dfa6-4c56-805b-3d58fce78ebf)
这几个是不是都得改成配置，但是他们的内容又不是一样的结构，可能需要出新的接口

**Comment by iRuxu** [comment]
## 检查确认
https://www.jx3box.com/macro/19382

+ 圈人卡：需要更新editor库，看文末的圈人
+ 评论：是否需要更新comment库
+ 侧边栏

- [x] 已完成

**Comment by iRuxu** [comment]
## 其它栏目同步

确认完成后部署到
+ fb
+ bps
+ tool

- [x] 已完成

**Comment by iRuxu** [comment]
## 其它栏目同步

+ pvp

是vue3的

- [x] 已完成

**Comment by iRuxu** [comment]
## 论坛

侧边栏的效果现在不太对

- [x] 已完成

**Comment by iRuxu** [comment]
## 论坛

魔卡是需要独立的。

<img width="385" alt="image" src="https://github.com/user-attachments/assets/14b0bfe8-f537-4311-8831-5c4849f5a8fc" />


- [x] 已完成

**Comment by iRuxu** [comment]
## 勋章和称号

可以拓展到现在的表上

<img width="481" alt="image" src="https://github.com/user-attachments/assets/66ba5d85-bb3d-4d5f-9bdc-1db664bd8d3a" />

但是这个地方，设计只在这边入口来编辑，设计需要的字段！
设计不要去动运营那边的字段！


---------
勋章和称号用的是直接查询接口，没有走json


- [x] 已完成

**Comment by iRuxu** [comment]
## 首页

当没有活动时，会优先展示用户的主题

<img width="902" alt="image" src="https://github.com/user-attachments/assets/719fa162-e5b8-4617-bc67-f88a7cf64a05" />

- [x] 已完成
